version: '3'

services:
  api:
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    environment:
      NODE_ENV: "production"
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      UPLOADS_PATH: ${UPLOADS_PATH}
    env_file: .env
    volumes:
      - /media/ssd/uploads:${UPLOADS_PATH}
    networks:
      - npm-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: "0.0.0.0"
    networks:
      - npm-network

networks:
  npm-network:
    external: true
