version: '3'

services:
  api:
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: "production"
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
    env_file: .env
    build: .
    volumes:
      - ${HOST_UPLOAD_PATH}:/app/uploads
    networks:
      - npm-network
      - db-network

networks:
  npm-network:
    external: true
  db-network:
    external: true
